version: "3.9"
services:
  server:
    build: server/.
    restart: always
    ports:
      - "8000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    image: "mysql:latest"
    volumes:
      - mysql-volume:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 5s
      retries: 20
  apache:
    build: apache/.
    ports:
      - '80:80'
    volumes:
      - ./apache/website:/usr/local/apache2/htdocs
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  mysql-volume:
